# Generated by Django 4.0.1 on 2022-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='time_sent',
            field=models.DateTimeField(),
        ),
    ]
