# Generated by Django 4.0.1 on 2022-10-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.FloatField(blank='True', null='True'),
            preserve_default='True',
        ),
    ]
