# Generated by Django 4.0.1 on 2022-10-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_price_alter_bid_bid_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction_id',
        ),
        migrations.AlterField(
            model_name='bid',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
