# Generated by Django 4.0.1 on 2022-11-03 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bid_auction_id_alter_bid_time_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='bidder',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='time_sent',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing_id',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
            preserve_default='True',
        ),
    ]
