# Generated by Django 4.0.1 on 2022-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='price',
            field=models.FloatField(error_messages={'name': {'max_length': 'The price must be between 0 and 999.99.'}}, help_text='Sample: 999.99', null=True),
        ),
    ]
